/**
 * Auto-gen — generate AI instruction files from the knowledge graph.
 * Writes sections to CLAUDE.md, .cursorrules, or AGENTS.md so your AI
 * assistant navigates via structure instead of keyword grepping.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { GraphStore } from "./graph/store.js";

const AUTOGEN_START = "<!-- engram:start -->";
const AUTOGEN_END = "<!-- engram:end -->";

/**
 * Generate a compact architecture summary from the graph.
 */
export function generateSummary(store: GraphStore): string {
  const stats = store.getStats();
  const gods = store.getGodNodes(8);
  const allNodes = store.getAllNodes();
  const allEdges = store.getAllEdges();

  // Group files by directory
  const filesByDir = new Map<string, string[]>();
  for (const node of allNodes) {
    if (node.kind === "file" && node.sourceFile) {
      const dir = node.sourceFile.split("/").slice(0, -1).join("/") || ".";
      if (!filesByDir.has(dir)) filesByDir.set(dir, []);
      filesByDir.get(dir)!.push(node.label);
    }
  }

  // Count by kind
  const kindCounts = new Map<string, number>();
  for (const node of allNodes) {
    kindCounts.set(node.kind, (kindCounts.get(node.kind) ?? 0) + 1);
  }

  // Find key relationships
  const importEdges = allEdges.filter((e) => e.relation === "imports");
  const mostImported = new Map<string, number>();
  for (const edge of importEdges) {
    mostImported.set(edge.target, (mostImported.get(edge.target) ?? 0) + 1);
  }
  const topImported = [...mostImported.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const lines: string[] = [
    AUTOGEN_START,
    "## Codebase Structure (auto-generated by engram)",
    "",
    `**Graph:** ${stats.nodes} nodes, ${stats.edges} edges | ${stats.extractedPct}% extracted, ${stats.inferredPct}% inferred`,
    "",
  ];

  // God nodes
  if (gods.length > 0) {
    lines.push("**Core entities:**");
    for (const g of gods) {
      lines.push(`- \`${g.node.label}\` (${g.node.kind}, ${g.degree} connections) — ${g.node.sourceFile}`);
    }
    lines.push("");
  }

  // Directory structure
  if (filesByDir.size > 0) {
    lines.push("**Structure:**");
    for (const [dir, files] of [...filesByDir.entries()].sort()) {
      lines.push(`- \`${dir}/\` — ${files.join(", ")}`);
    }
    lines.push("");
  }

  // Most imported
  if (topImported.length > 0) {
    lines.push("**Key dependencies (most imported):**");
    for (const [target, count] of topImported) {
      const node = store.getNode(target);
      lines.push(`- \`${node?.label ?? target}\` (imported by ${count} files)`);
    }
    lines.push("");
  }

  // Decisions and patterns (if mined)
  const decisions = allNodes.filter((n) => n.kind === "decision");
  const patterns = allNodes.filter((n) => n.kind === "pattern");
  const mistakes = allNodes.filter((n) => n.kind === "mistake");

  if (decisions.length > 0) {
    lines.push("**Decisions:**");
    for (const d of decisions.slice(0, 5)) {
      lines.push(`- ${d.label}`);
    }
    lines.push("");
  }

  if (patterns.length > 0) {
    lines.push("**Patterns:**");
    for (const p of patterns.slice(0, 5)) {
      lines.push(`- ${p.label}`);
    }
    lines.push("");
  }

  if (mistakes.length > 0) {
    lines.push("**Known issues:**");
    for (const m of mistakes.slice(0, 3)) {
      lines.push(`- ${m.label}`);
    }
    lines.push("");
  }

  lines.push(
    "**Tip:** Run `engram query \"your question\"` for structural context instead of reading files.",
    AUTOGEN_END,
  );

  return lines.join("\n");
}

/**
 * Write or update the engram section in an AI instruction file.
 */
export function writeToFile(filePath: string, summary: string): void {
  let content = "";
  if (existsSync(filePath)) {
    content = readFileSync(filePath, "utf-8");
  }

  // Replace existing engram section or append
  if (content.includes(AUTOGEN_START)) {
    content = content.replace(
      new RegExp(`${AUTOGEN_START}[\\s\\S]*?${AUTOGEN_END}`, "g"),
      summary
    );
  } else {
    content = content.trimEnd() + "\n\n" + summary + "\n";
  }

  writeFileSync(filePath, content);
}

/**
 * Auto-generate AI instructions for a project.
 * Detects which instruction file exists and updates it.
 */
export async function autogen(
  projectRoot: string,
  target?: "claude" | "cursor" | "agents"
): Promise<{ file: string; nodesIncluded: number }> {
  const { getStore } = await import("./core.js");
  const store = await getStore(projectRoot);

  try {
    const summary = generateSummary(store);
    const stats = store.getStats();

    let targetFile: string;
    if (target === "claude") {
      targetFile = join(projectRoot, "CLAUDE.md");
    } else if (target === "cursor") {
      targetFile = join(projectRoot, ".cursorrules");
    } else if (target === "agents") {
      targetFile = join(projectRoot, "AGENTS.md");
    } else {
      // Auto-detect
      if (existsSync(join(projectRoot, "CLAUDE.md"))) {
        targetFile = join(projectRoot, "CLAUDE.md");
      } else if (existsSync(join(projectRoot, ".cursorrules"))) {
        targetFile = join(projectRoot, ".cursorrules");
      } else if (existsSync(join(projectRoot, "AGENTS.md"))) {
        targetFile = join(projectRoot, "AGENTS.md");
      } else {
        targetFile = join(projectRoot, "CLAUDE.md");
      }
    }

    writeToFile(targetFile, summary);
    return { file: targetFile, nodesIncluded: stats.nodes };
  } finally {
    store.close();
  }
}
